# AWS Dev ?? ?? ??
cloud.aws.region.static=${AWS_REGION:ap-northeast-2}
cloud.aws.stack.auto=false
management.endpoint.health.show-details=when-authorized
logging.level.com.hanseonyoung.statuscheck=DEBUG

# AWS Dev ?? ???
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,https://dev-aws.cccr4.com,http://frontend.cccr4.com,https://frontend.cccr4.com}