spring.sql.init.mode=always
# ============================================
# READ DB (H2) Configuration
# ============================================
spring.datasource.read.driver-class-name=org.h2.Driver
spring.datasource.read.jdbc-url=jdbc:h2:mem:testdb;MODE=MariaDB
spring.datasource.read.username=sa
spring.datasource.read.password=
spring.datasource.read.continue-on-error=true

# ============================================
# METRICS DB (H2) Configuration
# ============================================
spring.datasource.metrics.driver-class-name=org.h2.Driver
spring.datasource.metrics.jdbc-url=jdbc:h2:mem:testdb;MODE=MariaDB
spring.datasource.metrics.username=sa
spring.datasource.metrics.password=
spring.datasource.metrics.continue-on-error=true

# ============================================
# JPA Configuration (for H2)
# ============================================
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;
#spring.datasource.url=jdbc:h2:file:/testdb;MODE=MySQL;
spring.datasource.url=jdbc:h2:file:${HOME}/testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.generate-unique-name=false

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

### need to active relevant sql query; schema.sql, data.sql

# H2 Console Enable
#spring.h2.console.enabled=true

## test properties
rtsp.port=554
rtsp.username=testuser
rtsp.password=testpass
rtsp.path=/sample/path
