# Dev ?? ?? ???
management.endpoint.health.show-details=when-authorized
logging.level.com.hanseonyoung.statuscheck=DEBUG

# Dev ?? ??? (????? ?? ?? ??)
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,http://dev-onprem.cccr4.com,http://frontend.cccr4.com,https://frontend.cccr4.com}